name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 29.0.3-alpine-3.24.1
          - erlang: 28.5.0.3-alpine-3.24.1
          - erlang: 27.3.4.14-alpine-3.24.1
          - erlang: 26.2.5.21-alpine-3.24.1
          - erlang: 25.3.2.21-alpine-3.22.5
          - erlang: 24.3.4.17-alpine-3.22.5
          - erlang: 23.3.4.20-alpine-3.16.9

    steps:
      - uses: actions/checkout@v7

      - name: Setup
        run: |
          make docker-setup DOCKER_OTP_VERSION=${{matrix.erlang}}

      - name: Test
        run: |
          make docker-test DOCKER_OTP_VERSION=${{matrix.erlang}}

      - name: Logs
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: ct-logs-${{matrix.erlang}}
          path: logs/*
